datamodule:
  # must use the absolute path of dataset to work with hydra
  zarr_path: ~/dev/garmentnets/data/garmentnets_dataset.zarr/Dress
  metadata_cache_dir: ~/local/.cache/metadata_cache_dir
  batch_size: 8
  num_workers: 4
  # sample size
  num_pc_sample: 6000
  num_volume_sample: 0
  num_surface_sample: 0
  num_mc_surface_sample: 0
  # data augumentation
  enable_augumentation: True
  random_rot_range: [-180,180]
  num_views: 4
  # common value 0.005
  pc_noise_std: 0
  # volume
  volume_size: 128
  volume_group: nocs_winding_number_field
  tsdf_clip_value: null
  volume_absolute_value: False
  include_volume: False
  # random seed
  static_epoch_seed: False
  # datamodule config
  dataset_split: [8,1,1]
  split_seed: 0

model:
  feature_dim: 128
  batch_norm: True
  dropout: True
  sa1_ratio: 0.5
  sa1_r: 0.05
  sa2_ratio: 0.25
  sa2_r: 0.1
  fp3_k: 1
  fp2_k: 3
  fp1_k: 3
  symmetry_axis: null
  nocs_bins: 64
  learning_rate: 0.0001
  nocs_loss_weight: 1
  grip_point_loss_weight: 1
  vis_per_items: 21
  max_vis_per_epoch_train: 10
  max_vis_per_epoch_val: 40
trainer:
  gpus: [0]
  resume_from_checkpoint: null
logger:
  offline: True
  name: null
  tags: []
